# Generated by Django 4.1.7 on 2023-04-15 08:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desired_loan", models.FloatField()),
                ("annual_income", models.FloatField()),
                (
                    "loan_will_be_used_for",
                    models.CharField(
                        choices=[
                            ("business_launching", "business_launching"),
                            ("house_buying", "house_buying"),
                            ("home_improvement", "home_improvement"),
                            ("investment", "investment"),
                            ("education", "education"),
                            ("other", "other"),
                        ],
                        default="business_launching",
                        max_length=250,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField(null="False")),
                ("email", models.EmailField(max_length=254)),
                (
                    "phoneNumber",
                    phone_field.models.PhoneField(
                        blank=True, help_text="Contact phone number", max_length=31
                    ),
                ),
                ("home_address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state_province", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=100)),
                (
                    "bank_url",
                    models.URLField(
                        default="https://www.absabank.co.ke/personal/borrow/personal-loan/"
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("interest_rate", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Features",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_amount", models.FloatField(default=25000)),
                ("max_amount", models.FloatField(default=150000)),
                ("low_interest_rate", models.FloatField()),
                ("illustration_rate", models.FloatField()),
                ("initiation_fee_perecentage_rate", models.FloatField()),
                ("monthly_service_fee", models.FloatField()),
                (
                    "bank_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Banks.bank",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Help",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("details", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Personal_expenditure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_salary",
                    models.FloatField(
                        default=10000,
                        validators=[django.core.validators.MinValueValidator(10000)],
                    ),
                ),
                ("rent_or_mortgage_expense", models.FloatField(default=0)),
                ("property_taxes", models.FloatField(default=0)),
                ("home_owner_insurance", models.FloatField(default=0)),
                ("water", models.FloatField(default=0)),
                ("electricity", models.FloatField(default=0)),
                ("household_supplies", models.FloatField(default=0)),
                ("dining_out", models.FloatField(default=0)),
                ("takeouts", models.FloatField(default=0)),
                ("personal_care", models.FloatField(default=0)),
                ("doctors_visits", models.FloatField(default=0)),
                ("insurance_premiums", models.FloatField(default=0)),
                ("entertainment", models.FloatField(default=0)),
                ("credit_cards", models.FloatField(default=0)),
                ("loan_debts", models.FloatField(default=0)),
                ("childcare", models.FloatField(default=0)),
                ("miscellaneous_expense", models.FloatField(default=0)),
                ("updated_salary", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("initiation_fee", models.FloatField()),
                ("service_fee", models.FloatField()),
                ("loan_amount", models.FloatField()),
                ("loan_period", models.IntegerField()),
                ("total_amount_payable", models.FloatField(blank=True, null=True)),
                ("monthly_installments", models.FloatField(blank=True, null=True)),
                ("total_amount", models.FloatField(blank=True, null=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Banks.bank"
                    ),
                ),
                (
                    "bank_features",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Banks.features"
                    ),
                ),
                (
                    "personal_expenses",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Banks.personal_expenditure",
                    ),
                ),
            ],
        ),
    ]
