# Generated by Django 4.1.7 on 2023-03-15 14:09

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):
    dependencies = [
        ("Banks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disired_loan", models.FloatField()),
                ("annual_income", models.FloatField()),
                (
                    "loan_will_be_used_for",
                    models.CharField(
                        choices=[
                            ("business_launching", "business_launching"),
                            ("house_buying", "house_buying"),
                            ("home_improment", "home_improment"),
                            ("investment", "investment"),
                            ("educucation", "educucation"),
                            ("other", "other"),
                        ],
                        default="business_launching",
                        max_length=250,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                (
                    "phoneNumber",
                    phone_field.models.PhoneField(
                        blank=True, help_text="Contact phone number", max_length=31
                    ),
                ),
                ("home_address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state_province", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name="Features",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_amount", models.FloatField()),
                ("max_amount", models.FloatField()),
                (
                    "low_interest_rate",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                (
                    "illustration_rate",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("amount_borrowed", models.FloatField()),
                ("initiation_fee", models.FloatField()),
                ("monthly_service_fee", models.FloatField()),
                ("amount_payable", models.FloatField()),
                ("monthly_installment_amount", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="bank",
            name="interestRate",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
