# Generated by Django 4.1.7 on 2023-03-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Banks", "0002_contact_help_remove_application_phonenumber"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="disired_loan",
            new_name="desired_loan",
        ),
        migrations.AlterField(
            model_name="application",
            name="loan_will_be_used_for",
            field=models.CharField(
                choices=[
                    ("business_launching", "business_launching"),
                    ("house_buying", "house_buying"),
                    ("home_improment", "home_improment"),
                    ("investment", "investment"),
                    ("education", "education"),
                    ("other", "other"),
                ],
                default="business_launching",
                max_length=250,
            ),
        ),
    ]
