# Generated by Django 4.1.7 on 2023-03-23 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loan_request",
            old_name="Loan_ammount",
            new_name="Loan_amount",
        ),
    ]
